const TOKEN = "8455897411:AAGdiajpZSQkXOJgs6RWvKj01Hel-b5SmAA";
const CHAT_ID = "-1003889484238";
const THREAD_ID = 50;

const TELEGRAM_URL = `https://api.telegram.org/bot${TOKEN}/sendMessage`;

async function sendMessage(text) {
  await fetch(TELEGRAM_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      chat_id: CHAT_ID,
      message_thread_id: THREAD_ID,
      text: text
    })
  });
}

async function checkMarkets() {
  try {

    // BTC price
    const btc = await fetch("https://api.coindesk.com/v1/bpi/currentprice/USD.json");
    const btcData = await btc.json();
    const btcPrice = btcData.bpi.USD.rate;

    // Gold price
    const gold = await fetch("https://api.metals.live/v1/spot/gold");
    const goldData = await gold.json();
    const goldPrice = goldData[0].price;

    const message = `
DAILY MARKET UPDATE

• Asset: XAUUSD
• Price: ${goldPrice}

• Asset: BTCUSD
• Price: ${btcPrice}

Market Insight:
Gold and Bitcoin remain key volatility assets for traders today.

Session: London / New York
Generated by: The 1% Elite Traders Circle
`;

    sendMessage(message);

  } catch (error) {
    console.log("Error:", error);
  }
}

setInterval(checkMarkets, 1800000);

checkMarkets();
